# Generated by Django 5.2.1 on 2025-05-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listsTrello', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('listsTrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='listsTrello.liststrello')),
                ('user', models.ManyToManyField(related_name='cards', to='users.user')),
            ],
        ),
    ]
